//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiai.tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifieDateTime { get; set; }
        public string SenderId { get; set; }
        public string SenderMessage { get; set; }
        public string Messagesourcename { get; set; }
        public string MessagesourceId { get; set; }
        public string BookaReply { get; set; }
        public string AiRequestId { get; set; }
        public string AiSessionId { get; set; }
        public string IntentName { get; set; }
        public string ActionName { get; set; }
        public string FulFilmentResponseName { get; set; }
        public string ActionExecuted { get; set; }
    }
}
